apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: worker-safety-integ

images:
- name: royvishu1224/plot-test
  newTag: 1ac799a

bases:
  - ../base

patchesStrategicMerge:
- app-deployment.yaml
- dev-mysql-deployment.yaml