apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: worker-safety-integ

images:
- name: royvishu1224/plot-test
  newTag: a88486d


patchesStrategicMerge:
- app-deployment.yaml
- dev-mysql-deployment.yaml
resources:
- ../base
