apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

images:
- name: royvishu1224/plot-test
  newTag: bdaf7fa


patchesStrategicMerge:
- app-deployment.yaml
- dev-mysql-deployment.yaml
resources:
- ../base
