apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: royvishu1224/plot-test:6b8fed7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 200m
              memory: 16Mi
            limits:
              cpu: 300m
              memory: 128Mi
          env:
          - name: MYSQL_DATABASE_DB
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: db_name
          - name: MYSQL_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: db_root_password
          - name: MYSQL_DATABASE_HOST
            value: mysql.default.svc.cluster.local
            # valueFrom:
            #   secretKeyRef:
            #     name: db-creds
            #     key: host
          - name: MYSQL_DATABASE_PORT
            value: '3306'
            # valueFrom:
            #   secretKeyRef:
            #     name: db-creds
            #     key: port
          # livenessProbe:
          #   httpGet:
          #     path: /liveness
          #     port: 5000
          #   initialDelaySeconds: 0
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 1
          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: 5000
          #   initialDelaySeconds: 0
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 1
