apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: royvishu1224/plot-test
  newTag: deb125b

resources:
- service.yaml
- deployment.yaml
- mysql-depl.yaml
- mysql-secrets.yaml
- mysql-service.yaml
- secrets.yaml
